"""добавили признак публикации

Revision ID: 46c17e13651b
Revises: 
Create Date: 2020-05-12 20:28:18.644796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c17e13651b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    op.create_unique_constraint(None, 'works', ['work'])
    op.add_column('works_list', sa.Column('director_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'works_list', 'directors', ['director_id'], ['director_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works_list', type_='foreignkey')
    op.drop_column('works_list', 'director_id')
    op.drop_constraint(None, 'works', type_='unique')
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
